baseURL = 'https://austinwilhelm.com/'
languageCode = 'en-us'
title = 'the willy weave'
theme = 'typo'

[taxonomies]
tag = 'tags'

# Google analytics code
googleAnalytics = "G-xxxxxxxxx"

[params]
# Meta description
description = "an adventure with words"

# Appearance settings
theme = 'auto'
colorPalette = 'catpuccin'
hideHeader = false

# Intro on main page, content is markdown
homeIntroTitle = 'hello friend'
homeIntroContent = """
I am a creator and dreamer, lit by passion to bring wonder to others.
"""

# Collection to display on home
homeCollectionTitle = 'words'
homeCollection = 'posts'

# Lists parameters
paginationSize = 100
listSummaries = true
listDateFormat = '2 Jan 2006'

# Breadcrumbs
breadcrumbs = true

# Social icons
[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/austin-wilhelm/"

[[params.social]]
name = "github"
url = "https://github.com/austinwilhelm"

# Main menu pages
[[params.menu]]
name = "home"
url = "/"

[[params.menu]]
name = "posts"
url = "/posts"

# [[params.menu]]
# name = "about"
# url = "/about"

# Syntax highligth on code blocks
[markup]
[markup.highlight]
style = 'algol'

# Giscus comments
[params.giscus]
enable = false
repo = "user/repo"
repoid = "repoId"
category = "General"
categoryid = "categoryId"
mapping = "pathname"
theme = "preferred_color_scheme"